name: Package

on: [push, pull_request]

jobs:

  build:

    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        # Checkout the git repository
        uses: actions/checkout@v2

      - name: Compiler setup
        # Download and install latest Swift compiler
        uses: fwal/setup-swift@v1.5.0

      - name: Build package
        # Build SPM package
        run: swift build

      - name: Execute tests
        # Run all unit tests
        run: swift test
