name: Package

on: [push, pull_request]

jobs:

  codegen:

    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: Install swift
        # Download Swift compiler, install it and update PATH
        if: matrix.os == 'ubuntu-latest'
        run: |
          wget https://swift.org/builds/swift-5.1.4-release/ubuntu1804/swift-5.1.4-RELEASE/swift-5.1.4-RELEASE-ubuntu18.04.tar.gz
          tar xzf swift-5.1.4-RELEASE-ubuntu18.04.tar.gz
          echo "::add-path::$(pwd)/swift-5.1.4-RELEASE-ubuntu18.04/usr/bin"

      - name: Generate order
        # Parse Plotly schema and generate ordering of Swift struct members
        working-directory: Sources/Codegen/
        run: python3 order.py

      - name: Generate names
        # Parse Plotly schema and generate names of Swift objects
        working-directory: Sources/Codegen/
        run: python3 name.py

      - name: Generate code
        # Parse Plotly schema and generate code for equivalent Swift objects
        working-directory: Sources/Codegen/
        run: swift run codegen

      - name: Check for changes
        # Check whether all generated code changes are committed to git
        run: git diff --quiet || git diff
