name: Package

on: [push, pull_request]

jobs:

  codegen:

    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        # Checkout the git repository
        uses: actions/checkout@v2

      - name: Compiler setup
        # Download and install latest Swift compiler
        uses: fwal/setup-swift@v1.5.0

      - name: Generate order
        # Parse Plotly schema and generate ordering of Swift struct members
        working-directory: Sources/Codegen/
        run: python3 order.py

      - name: Generate names
        # Parse Plotly schema and generate names of Swift objects
        working-directory: Sources/Codegen/
        run: python3 name.py

      - name: Generate code
        # Parse Plotly schema and generate code for equivalent Swift objects
        working-directory: Sources/Codegen/
        run: swift run codegen

      - name: Check changes
        # Check whether all changes in the generated Swift source code are comitted
        run: git diff --quiet || git diff
