name: Documentation

on: [release]

jobs:

  jazzy:

    runs-on: macos-latest

    steps:
      - name: Checkout repository
        # Checkout the git repository
        uses: actions/checkout@v2

      - name: Generate and publish documentation
        # Generate documentation with Jazzy and then publish it on gh-pages branch
        uses: Steven0351/publish-jazzy-docs@v1.1.1
        with:
          personal_access_token: ${{ secrets.JAZZY_TOKEN }}
          config: .jazzy.yml
